#! /bin/bash

of=index.shtml
files=`grep \\lecture{ lectures.tex | grep -v % | sed 's/\\\lecture{//g' | sed 's/}//g'`

cat > $of <<EOF
<HTML>
<HEAD>
<TITLE>Lecture Notes
</TITLE>
</HEAD>

<!--#include virtual="/notes/comp3212/header.htx" -->

<H1 align="center">Lecture Notes</H1>

<h2> Notes for Computational Biology</h2>


<ol>
EOF

for f in $files; do
    lesson=`head $f.tex | grep 'lesson{' | sed 's/.lesson{//' | sed 's/}//'`
    keywords=`head -35 $f.tex | grep 'keywords{' | sed 's/.keywords{//' | sed 's/}//'`
    echo "$lesson: $keywords"
    echo "<li><b>$lesson</b>: $keywords" >> $of
    echo "<ul> <li>"  >> $of
    if [ -f videos/${f}.mp4 ]; then
	vf="videos/${f}Video.shtml"
	cat > $vf <<EOF
<HTML>
<HEAD>
<TITLE>Videos
</TITLE>
</HEAD>

<!--#include virtual="/notes/comp3212/header.htx" -->

<H1 align="center">Video for Advance Machine Learning</H1>

<h3><b>$lesson</b>: $keywords</h3>

<div>
 <video width="500" controls>
       <source src="${f}.mp4" type="video/mp4">
       Your browser does not support HTML5 video.
    </video>
</div>

<div>
<ul>
     <li> <a href="../${f}.pdf">Lecture PDF</a>, </li>
     <li> <a href="../${f}_prn.pdf">Printable PDF</a>, </li>
     <li> <a href="../${f}_prn_4.pdf">(4 per page)</a></li>
     <li> <a href="../${f}_prn_8.pdf">(8 per page)</a></li>
   </ul>

   <p>
</div>
<div>
 <h4> <a
 href=https://secure.ecs.soton.ac.uk/notes/comp3212/lectures/>Back to
 Lecture Notes Page</a></h4>
</div>
<!--#include virtual="/notes/comp3212/footer.htx" -->

</HTML>
EOF
	scp $vf apb1@stafflogin.ecs.soton.ac.uk:/notes/comp3212/lectures/$vf
	echo "<a href=\"${vf}\">Video</a>," >> $of
    fi
    cat >> $of <<EOF
     <a href="${f}.pdf">Lecture PDF</a>, 
     <a href="${f}_prn.pdf">Printable PDF</a>, 
     <a href="${f}_prn_4.pdf">(4 per page)</a>
     <a href="${f}_prn_8.pdf">(8 per page)</a></li>
   </ul>
EOF
    if [ -e ${f}-subsidiary.pdf ]; then
    cat >> $of <<EOF
     <ul> <li> <a href="${f}-subsidiary.pdf">Subsidiary notes on lecture</a></li>
     </ul>
EOF
    fi

    echo "</li>" >> $of 
done

cat >> $of <<EOF

<!--#include virtual="/notes/comp3212/footer.htx" -->

</HTML>
EOF
scp index.shtml apb1@stafflogin.ecs.soton.ac.uk:/notes/comp3212/lectures/index.shtml
